apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ProductOrdering-RetrieveProductOrdersBindingQSService
  description: ProductOrdering-RetrieveProductOrdersBindingQSService
  namespace: daas
spec:
  type: service
  lifecycle: production
  owner: TDP
  system: default/DAAS
