apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: OfferingsController
  description: OfferingsController
  namespace: ms-engine-retentionoffers-fi
spec:
  type: service
  lifecycle: production
  owner: TDP
  system: default/Motor-de-Ofertas
  subcomponentOf: motor-de-ofertas/ms-engine-retentionoffers-fi
  providesApis:
  - ms-engine-retentionoffers-fi/OfferingsController
  consumesApis:
  - ms-engine-elegibleoffers-fi/getOfferingsUsingGET
  - ms-engine-master-offers/getOfferingsUsingGET_1
  - ProducInventory/products
