apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: DevicesApiController
  description: DevicesApiController
  namespace: ms-engine-devices
spec:
  type: service
  lifecycle: production
  owner: TDP
  system: default/Motor-de-Ofertas
  subcomponentOf: motor-de-ofertas/ms-engine-devices
  providesApis:
  - ms-engine-devices/DevicesApiController
  consumesApis: []
