apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: retrieveCommitmentPenalties
  description: retrieveCommitmentPenalties
  namespace: ms-engine-penalty-inquiry
spec:
  type: service
  lifecycle: production
  owner: TDP
  system: default/Motor-de-Ofertas
  subcomponentOf: motor-de-ofertas/ms-engine-penalty-inquiry
  providesApis:
  - ms-engine-penalty-inquiry/retrieveCommitmentPenalties
  consumesApis:
  - OrderServicesService/retrieveCommitmentPenalty
