apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: retrieveCommitmentPenalty
  description: retrieveCommitmentPenalty
  namespace: orderservicesservice
spec:
  type: service
  lifecycle: production
  owner: TDP
  system: default/ESB-BSS
  subcomponentOf: esb-bss/OrderServicesService
  providesApis:
  - OrderServicesService/retrieveCommitmentPenalty
  consumesApis: []
