apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: getAccountBalance
  description: getAccountBalance
  namespace: balancemanagmentservice
spec:
  type: Info
  lifecycle: production
  owner: TDP
  system: default/ESB-BSS
  definition: "| \n\t\tpath: http://esbprodbm.simple.gp.inet/ChargeCalculationAndBalanceManagement/BalanceManagement/V1"
